### ISSUE TITLE
Seeing no messages in the .html file

### ISSUE THREAD

**Issue by hyoukafuwa** [cocciasecca/WhatsApp-Chat-Converter-txt-to-HTML-with-media#1]
After running the script which is in Italian for some reason, there are no messages loaded in the .html file

**Comment by cocciasecca** [comment]
Hi there, sorry I left part of the program in Italian, but I just translated it. What platform are you exporting chat from?
Edit: I don't actually have an English chat.txt file so the 'omitted media'/'file not present' media flag only works in Italian, but all the rest of the script should work fine.

**Comment by hyoukafuwa** [comment]
I have exported a group chat from WhatApp on my phone and uploaded it onto my computer. Thanks for answering so quickly.

**Comment by cocciasecca** [comment]
I mean which operating system, Android or iOS? Because each one has a different date formatting, and if the date is not recognised properly, then the messages conversion never starts.

**Comment by hyoukafuwa** [comment]
Oh, it was Android.

**Comment by cocciasecca** [comment]
So your chat.txt should look like this, right?
```
25/06/24, 21:10 - I messaggi e le chiamate sono crittografati end-to-end. Nessuno al di fuori di questa chat, nemmeno WhatsApp, può leggerne o ascoltarne il contenuto. Tocca per saperne di più.
25/06/24, 21:10 - 
25/06/24, 21:10 - Person 1: Ciao
25/06/24, 21:10 - Person 2: Ciao, come stai?
25/06/24, 21:10 - Person 1: Io bene, tu?
25/06/24, 21:11 - Person 2: Io pure, grazie
25/06/24, 21:11 - Person 1: <Media omessi>
25/06/24, 21:12 - Person 1: Questo è il mio gatto
25/06/24, 21:12 - Person 2: <Media omessi>
```

**Comment by hyoukafuwa** [comment]
Not exactly, the timestamps look different

```
01.10.20, 11:03 - anonym: hello
01.10.20, 11:03 - anonym: hello
01.10.20, 11:03 - anonym: ‎hello
01.10.20, 11:03 - anonym: hello
```

**Comment by cocciasecca** [comment]
ok that's why, but the date format is day month year, right?

**Comment by hyoukafuwa** [comment]
Yes, that is correct. These messages are back from 2020.

**Comment by cocciasecca** [comment]
Try it now, should work.
Let me know if it works, so I can close the issue👌

**Comment by hyoukafuwa** [comment]
Working now. Thank you for fixing this. There's not a lot of simple solutions out there to convert WhatsApp .txt to .html. 👌🏻

**Comment by hyoukafuwa** [comment]
Oh, something to mention. It seems it doesn't handle special characters that are common in my language well. 
![grafik](https://github.com/cocciasecca/WhatsApp-Chat-Converter-txt-to-HTML-with-media/assets/47471351/2372ee31-1ab4-4c88-9a36-a00e0463aec1)

**Comment by cocciasecca** [comment]
Try to refresh the page one or two times; even in my language, some characters like 'à' or 'é' and so on are not displayed correctly on the first page loading.

**Comment by hyoukafuwa** [comment]
Tried it, doesn't seem to work, though. If you need to know, the mesages are in German.

**Comment by cocciasecca** [comment]
That's weird, what is the character? Because I tried a lot of special characters, so there should be no problem in visualising them. Maybe if it's a very long chat try refreshing even something like 5 times and it should read fine.

**Comment by hyoukafuwa** [comment]
It's ö, ä and ü. Refreshing doesn't work, unfortunately.

**Comment by cocciasecca** [comment]
Try rerunning the script, or changing browser. I tried on Firefox and Brave, works on both.
<img width="178" alt="immagine" src="https://github.com/cocciasecca/WhatsApp-Chat-Converter-txt-to-HTML-with-media/assets/75637780/2fb9ec19-c0ac-4782-a6a6-af7b13376c4b">

**Comment by hyoukafuwa** [comment]
Okay, when I open the file locally, it works, but I'm running it on a web server. That seemed to be reason it didn't get displayed right. After adding `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` into the .html file, it gets shown correctly now.
Problem solved.

**Comment by cocciasecca** [comment]
Thank you so much for providing the fix, adding it to the code right now and closing the issue.👍
